version: '3.8'
services:
  database:
    container_name: database
    image: postgres:alpine
    restart: always
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  api:
    container_name: api
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - database
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/code
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
